server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/his?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: mysql
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
mybatis:
  configuration:
    map-underscore-to-camel-case: true
